# -*- coding: utf-8 -*-

DERIBIT_CLIENT_ID = "PmyJIl5T"
DERIBIT_CLIENT_SECRET = "7WBI4N_YT8YB5nAFq1VjPFedLMxGfrxxCbreMFOYLv0"
SYMBOL = 'BTC'

DERIBIT_ACCOUNT_ID = 'mogu1988'
SEASON_FUTURE = 'BTC-26JUN20'
